"""题目服务"""
import json
from sqlalchemy.orm import Session
from ..models.question import Question
from ..schemas.question import QuestionOut, QuestionDetail, QuestionGenerateRequest, QuestionGenerateResponse
from ..knowledge.retriever import retrieve_for_question


def get_questions(
    db: Session,
    module: str = None,
    type: str = None,
    difficulty: int = None,
    skip: int = 0,
    limit: int = 20,
) -> list[QuestionOut]:
    """查询题目列表，支持筛选"""
    query = db.query(Question)
    if module:
        query = query.filter(Question.module == module)
    if type:
        query = query.filter(Question.type == type)
    if difficulty:
        query = query.filter(Question.difficulty == difficulty)
    query = query.order_by(Question.created_at.desc()).offset(skip).limit(limit)
    return [QuestionOut.model_validate(q) for q in query.all()]


def get_question_detail(db: Session, question_id: int) -> QuestionDetail:
    """获取题目详情，包含关联知识卡片"""
    question = db.query(Question).filter(Question.id == question_id).first()
    if not question:
        raise ValueError(f"题目 {question_id} 不存在")

    # 获取关联知识
    tags = []
    if question.knowledge_tags:
        try:
            tags = json.loads(question.knowledge_tags)
        except json.JSONDecodeError:
            pass

    knowledge_cards = retrieve_for_question(tags, n_results=4)

    detail = QuestionDetail.model_validate(question)
    detail.knowledge_cards = knowledge_cards
    return detail


def seed_questions(db: Session) -> int:
    """初始化种子题目（仅当题库为空时执行）"""
    existing = db.query(Question).count()
    if existing > 0:
        return existing

    seed_data = [
        # 自然遗产 - 文化解说题
        {"title_zh": "向国际游客介绍四川大熊猫栖息地及其全球生态意义", "title_en": "Introduce the Sichuan Giant Panda Sanctuaries and their global ecological significance to international tourists", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "欧美普通游客", "difficulty": 2, "knowledge_tags": '["nat_001", "nat_006"]', "scenario": "你是成都熊猫基地的双语解说员，一群来自欧洲的游客正在参观，请用英语向他们介绍大熊猫栖息地和保护成就。"},
        {"title_zh": "九寨沟震后重生：自然修复力的全球启示", "title_en": "Jiuzhaigou's Post-Earthquake Rebirth: What Nature's Resilience Tells the World", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际环保组织代表", "difficulty": 3, "knowledge_tags": '["nat_002"]', "scenario": "在一次国际生态旅游论坛上，你作为中方代表，用中英双语介绍九寨沟2017年地震后的自然恢复过程。"},
        {"title_zh": "都江堰：2280年仍在运行的无坝水利奇迹", "title_en": "Dujiangyan: The 2,280-Year-Old Dam-Free Irrigation Wonder Still Working Today", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际工程界人士", "difficulty": 3, "knowledge_tags": '["nat_008", "nat_009"]', "scenario": "在国际水利工程大会上，用英文介绍都江堰'无坝引水'的工程哲学及其对当代可持续发展的启示。"},
        {"title_zh": "稻城亚丁：蓝色星球上的最后一片净土", "title_en": "Daocheng Yading: The Last Pristine Land on the Blue Planet", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际旅游爱好者", "difficulty": 2, "knowledge_tags": '["nat_007"]', "scenario": "在一档国际旅游节目中，用中英双语向全球观众介绍稻城亚丁的自然景观和藏族文化。"},

        # 自然遗产 - 更多文化解说题
        {"title_zh": "黄龙：金色钙华滩上的地质奇迹", "title_en": "Huanglong: The Geological Wonder on the Golden Travertine Shoal", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际地质学爱好者", "difficulty": 2, "knowledge_tags": '["nat_003"]', "scenario": "你在一档国际自然纪录片中担任双语解说，向全球观众介绍黄龙3400多个钙华彩池的地质成因和美学价值。"},
        {"title_zh": "峨眉山-乐山大佛：文化与自然双遗产的双语解读", "title_en": "Mount Emei and Leshan Giant Buddha: A Bilingual Guide to a Mixed UNESCO Heritage Site", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际游客与文化学者", "difficulty": 3, "knowledge_tags": '["nat_004"]', "scenario": "你作为峨眉山景区的双语导游，带领一群国际游客游览峨眉山和乐山大佛，介绍其作为中国仅有的四个'双遗产'之一的独特价值。"},
        {"title_zh": "蜀道：李白笔下的'天路'与线性文化遗产", "title_en": "The Shu Roads: Li Bai's 'Road to Heaven' and China's Linear Cultural Heritage", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际文化遗产保护专家", "difficulty": 4, "knowledge_tags": '["nat_005"]', "scenario": "在蜀道申遗国际专家考察中，用中英双语介绍蜀道的历史价值——从战国古栈道到翠云廊千年古柏。"},
        {"title_zh": "大熊猫国家公园：中国生态文明建设的新范式", "title_en": "Giant Panda National Park: A New Paradigm for China's Ecological Civilization", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际生态保护学者", "difficulty": 3, "knowledge_tags": '["nat_006"]', "scenario": "在国际国家公园论坛上，用英文介绍大熊猫国家公园如何通过'生态廊道'解决栖息地碎片化问题，以及它对全球保护地管理的启示。"},
        {"title_zh": "青城山：道教发源地的'天下幽'境", "title_en": "Mount Qingcheng: The Birthplace of Taoism and 'the Most Serene Mountain Under Heaven'", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际哲学与宗教文化爱好者", "difficulty": 3, "knowledge_tags": '["nat_009"]', "scenario": "你主持一档国际宗教文化旅游节目，用双语介绍青城山作为道教发源地的文化意义和'青城天下幽'的山水美学。"},
        {"title_zh": "蜀南竹海：《卧虎藏龙》取景地的竹文化之旅", "title_en": "Shunan Bamboo Sea: A Bamboo Culture Journey at a 'Crouching Tiger, Hidden Dragon' Filming Location", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际电影与自然爱好者", "difficulty": 2, "knowledge_tags": '["nat_010"]', "scenario": "你在一档国际旅游节目中，用英文介绍蜀南竹海——从《卧虎藏龙》的竹林对决到宜宾'中国竹都'的竹文化传承。"},
        {"title_zh": "若尔盖湿地：黄河上游的'高原之肾'", "title_en": "Zoige Wetlands: The 'Plateau Kidney' of the Upper Yellow River", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际气候变化与生态学者", "difficulty": 4, "knowledge_tags": '["nat_011"]', "scenario": "在一场国际湿地保护大会上，用中英双语介绍若尔盖泥炭湿地的碳汇价值、黑颈鹤保护与全球气候变化的关联。"},
        {"title_zh": "海螺沟冰川：亚洲最低海拔冰川的'冰与火'奇观", "title_en": "Hailuogou Glacier: The 'Ice and Fire' Spectacle of Asia's Lowest-Altitude Glacier", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际气候科学与户外探险爱好者", "difficulty": 3, "knowledge_tags": '["nat_012"]', "scenario": "在国际地理探索频道节目中，用英文介绍海螺沟冰川与温泉共存的'冰火两重天'奇观，以及冰川退缩反映的全球变暖现实。"},
        {"title_zh": "四姑娘山：'蜀山之后'的攀登圣地与生态保护区", "title_en": "Mount Siguniang: The 'Queen of Sichuan Peaks' — A Climbing Mecca and Ecological Sanctuary", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际登山与户外运动爱好者", "difficulty": 2, "knowledge_tags": '["nat_014"]', "scenario": "你在一档国际户外探险节目中，用双语介绍四姑娘山幺妹峰的世界级攀登路线和四姑娘山作为大熊猫栖息地的双重价值。"},
        {"title_zh": "邛海-泸山：'月城'西昌的山水诗意与航天梦想", "title_en": "Qionghai Lake and Lushan Mountain: The Poetic Landscape and Space Dreams of 'Moon City' Xichang", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际旅游与航天爱好者", "difficulty": 2, "knowledge_tags": '["nat_015"]', "scenario": "在一档国际文化旅游节目中，用双语介绍西昌'月城'的独特魅力——从邛海候鸟到卫星发射中心的'天地对话'。"},

        # 历史文脉 - 更多文化解说题
        {"title_zh": "金沙遗址：太阳神鸟金饰背后的古蜀密码", "title_en": "Jinsha Site: Decoding Ancient Shu Through the Sunbird Gold Foil", "type": "cultural_explanation", "module": "history", "language_direction": "bilingual", "target_audience": "国际考古与博物馆爱好者", "difficulty": 3, "knowledge_tags": '["hist_002"]', "scenario": "你在金沙遗址博物馆担任双语解说员，向国际游客介绍太阳神鸟金饰——这件仅0.02厘米厚、重20克的金饰为何成为中国文化遗产标志。"},
        {"title_zh": "杜甫草堂：诗圣在成都的'诗意栖居'", "title_en": "Du Fu Thatched Cottage: The Poet Sage's 'Poetic Dwelling' in Chengdu", "type": "cultural_explanation", "module": "history", "language_direction": "bilingual", "target_audience": "国际文学与诗歌爱好者", "difficulty": 2, "knowledge_tags": '["hist_004"]', "scenario": "在国际诗歌节的文化参访环节，你用双语向各国诗人介绍杜甫草堂——杜甫在此创作240首诗，写就了'安得广厦千万间'的不朽名句。"},
        {"title_zh": "安岳石刻：散落在乡野的'东方维纳斯'与晚期石窟艺术", "title_en": "Anyue Stone Carvings: The 'Oriental Venus' Scattered in the Countryside and China's Late Cave-Temple Art", "type": "cultural_explanation", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际艺术史与石窟研究学者", "difficulty": 4, "knowledge_tags": '["hist_006"]', "scenario": "在国际石窟艺术研讨会上，用英文介绍安岳石刻——10万余尊造像、230余处石窟点，如何填补了中国石窟艺术史在唐宋以后的叙事空白。"},
        {"title_zh": "茶马古道川藏线：背夫踏出的汉藏交流血脉", "title_en": "The Sichuan-Tibet Tea Horse Road: The Lifeblood of Han-Tibetan Exchange Forged by Porters", "type": "cultural_explanation", "module": "history", "language_direction": "bilingual", "target_audience": "国际文化遗产与人类学者", "difficulty": 4, "knowledge_tags": '["hist_007"]', "scenario": "在一带一路文化遗产论坛上，用双语介绍茶马古道川藏线——1300年的'以茶易马'如何塑造了汉藏民族交往交流交融的历史。"},
        {"title_zh": "剑门关：'一夫当关'的千年战史与蜀道传奇", "title_en": "Jianmen Pass: A Thousand Years of Military History and the Legend of the Shu Roads", "type": "cultural_explanation", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际军事历史与地理爱好者", "difficulty": 3, "knowledge_tags": '["hist_008"]', "scenario": "在一档国际军事历史节目中，用英文介绍剑门关——诸葛亮修筑、从未被正面攻破的'蜀北屏障'，以及李白'一夫当关、万夫莫开'的诗句如何塑造了一个文化符号。"},
        {"title_zh": "泸定桥：从康熙御笔到红军飞夺的三百年传奇", "title_en": "Luding Bridge: A 300-Year Legend from Kangxi's Imperial Inscription to the Red Army's Daring Capture", "type": "cultural_explanation", "module": "history", "language_direction": "bilingual", "target_audience": "国际历史与工程爱好者", "difficulty": 3, "knowledge_tags": '["hist_009"]', "scenario": "在一档国际历史纪录片中，用双语讲述泸定桥的故事——1705年康熙下令建造的铁索桥，如何成为1935年红军长征中最具传奇色彩的战场。"},
        {"title_zh": "自贡恐龙博物馆：一亿六千万年前的'恐龙公墓'", "title_en": "Zigong Dinosaur Museum: A 160-Million-Year-Old 'Dinosaur Graveyard'", "type": "cultural_explanation", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际古生物与自然科学爱好者", "difficulty": 2, "knowledge_tags": '["hist_010"]', "scenario": "你在一档国际科普节目中，用英文介绍自贡恐龙博物馆——世界三大恐龙遗址博物馆之一，建在大山铺中侏罗世化石群的原址上。"},
        {"title_zh": "李白故里江油：'诗仙'的巴蜀基因与全球影响力", "title_en": "Li Bai's Hometown Jiangyou: The Ba-Shu Roots and Global Influence of the 'Poet Immortal'", "type": "cultural_explanation", "module": "history", "language_direction": "bilingual", "target_audience": "国际文学与文化爱好者", "difficulty": 2, "knowledge_tags": '["hist_011"]', "scenario": "在一档国际文化人物节目中，用双语介绍李白的巴蜀渊源——从江油青莲镇的'铁杵磨成针'到其诗歌被译成30多种语言的全球传播史。"},

        # 非遗技艺 - 更多文化解说题
        {"title_zh": "蜀绣：从皇家贡品到国际时尚的千年丝路", "title_en": "Shu Embroidery: A Thousand-Year Silk Road from Imperial Tribute to International Fashion", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际时尚与传统工艺爱好者", "difficulty": 2, "knowledge_tags": '["ich_002"]', "scenario": "在一场国际非遗与时尚跨界论坛上，用双语介绍蜀绣——从122种针法到双面异色绣，从汉代起源到当代设计师的国际合作。"},
        {"title_zh": "绵竹年画：巴蜀民间的'色彩哲学'", "title_en": "Mianzhu New Year Prints: The 'Color Philosophy' of Ba-Shu Folk Art", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际民间艺术与版画爱好者", "difficulty": 2, "knowledge_tags": '["ich_006"]', "scenario": "在一档国际民间艺术节目中，用英文介绍绵竹年画——中国四大年画之一，以'一黑二白三金黄'的手工彩绘工序和'填水脚'写意技法著称。"},
        {"title_zh": "道明竹编：从日常器物到威尼斯建筑双年展", "title_en": "Daoming Bamboo Weaving: From Everyday Utensils to the Venice Architecture Biennale", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际设计与可持续发展领域观众", "difficulty": 3, "knowledge_tags": '["ich_007"]', "scenario": "在一场国际可持续设计论坛上，用双语介绍道明竹编——从2000年历史的崇州竹编到2018年威尼斯建筑双年展'竹里'装置，传统工艺如何走向当代建筑。"},
        {"title_zh": "藏羌织绣：无文字民族的'视觉史诗'", "title_en": "Tibetan-Qiang Embroidery: The 'Visual Epic' of Peoples Without Writing", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际人类学与纺织艺术爱好者", "difficulty": 3, "knowledge_tags": '["ich_008"]', "scenario": "在一场国际民族艺术展览开幕式上，用双语介绍藏羌织绣——从羌族挑花的'反面挑花正面看'到藏族氆氇的手工纺染，每一针都是族群记忆的载体。"},
        {"title_zh": "彝族火把节：'东方狂欢节'的古老火崇拜与现代旅游", "title_en": "Yi Torch Festival: The Ancient Fire Worship and Modern Tourism of the 'Oriental Carnival'", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际民俗与文化旅游爱好者", "difficulty": 2, "knowledge_tags": '["ich_009"]', "scenario": "在一档国际节庆文化节目中，用双语介绍凉山彝族火把节——从毕摩的祭火仪式到万人持火巡游的'东方狂欢节'。"},
        {"title_zh": "成都漆艺：三千年不绝的'大漆之道'", "title_en": "Chengdu Lacquer Art: The 3,000-Year Unbroken 'Way of Lacquer'", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际工艺美术与设计爱好者", "difficulty": 3, "knowledge_tags": '["ich_010"]', "scenario": "在一档国际手工艺纪录片中，用英文介绍成都漆艺——从金沙遗址3000年前的漆器残片到汉代'蜀郡工官'的巅峰，以及'雕花填彩'和'金银平脱'的精妙技法。"},

        # 历史文脉 - 即兴串场题
        {"title_zh": "三星堆考古直播：连接古蜀文明与全球观众", "title_en": "Sanxingdui Archaeological Live Stream: Connecting Ancient Shu with a Global Audience", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "全球考古爱好者", "difficulty": 4, "knowledge_tags": '["hist_001", "hist_002"]', "scenario": "你是三星堆考古发掘直播的双语主持人，在祭祀坑新文物出土的间隙，用中英双语向全球观众介绍三星堆文明的独特性和未解之谜。"},
        {"title_zh": "武侯祠国际三国文化节开幕式串场", "title_en": "Opening Ceremony Bridge for the Wuhou Shrine International Three Kingdoms Culture Festival", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "中日韩三国文化爱好者", "difficulty": 3, "knowledge_tags": '["hist_003"]', "scenario": "你主持成都武侯祠国际三国文化节开幕式，需要在川剧变脸表演和日本《三国志》Cosplay走秀之间用双语串场。"},
        {"title_zh": "阆中古城入选世界文化遗产预备名录新闻发布会", "title_en": "Press Conference on Langzhong Ancient City's Inclusion in UNESCO Tentative List", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "国际媒体记者", "difficulty": 4, "knowledge_tags": '["hist_005"]', "scenario": "你就阆中古城入选UNESCO世界遗产预备名录主持双语新闻发布会，需要介绍阆中'春节发源地'和风水之城的独特价值。"},

        # 自然遗产 - 即兴串场题
        {"title_zh": "国际山地旅游联盟年会：从九寨沟到黄龙的生态串场", "title_en": "International Mountain Tourism Alliance Annual Conference: Ecological Bridges from Jiuzhaigou to Huanglong", "type": "impromptu_bridge", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际旅游行业领袖", "difficulty": 4, "knowledge_tags": '["nat_002", "nat_003"]', "scenario": "你主持国际山地旅游联盟年会，上一个环节介绍了九寨沟的震后修复，下一个环节是黄龙钙华地貌保护案例。请用双语串场，衔接两个世界自然遗产的内在联系。"},
        {"title_zh": "全球国家公园论坛：大熊猫国家公园与黄石公园的经验对话", "title_en": "Global National Park Forum: Bridging the Giant Panda National Park and Yellowstone Dialogue", "type": "impromptu_bridge", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际保护地管理专家", "difficulty": 4, "knowledge_tags": '["nat_006"]', "scenario": "你在全球国家公园论坛主持，一位美国黄石公园管理者刚分享了经验，下一位是中国大熊猫国家公园负责人。请用双语串场，为两种保护地模式的对话建立桥梁。"},
        {"title_zh": "'蜀道申遗'国际考察团欢迎晚宴双语主持", "title_en": "Bilingual Hosting for the 'Shu Roads World Heritage Nomination' International Delegation Welcome Dinner", "type": "impromptu_bridge", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "UNESCO评审专家与多国外交官", "difficulty": 5, "knowledge_tags": '["nat_005"]', "scenario": "你主持蜀道申遗国际专家考察团欢迎晚宴，需要在川菜品鉴环节和古琴演奏环节之间用双语串场，将蜀道的千年历史与晚宴的文化氛围自然融合。"},
        {"title_zh": "国际道教文化节：青城山与武当山的跨时空对话", "title_en": "International Taoist Culture Festival: A Cross-Temporal Dialogue Between Mount Qingcheng and Wudang Mountain", "type": "impromptu_bridge", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际宗教文化与哲学学者", "difficulty": 3, "knowledge_tags": '["nat_009"]', "scenario": "在国际道教文化节开幕式上，武当山的太极拳表演刚结束，接下来是青城山的洞经音乐。请用双语串场，对比两大名山的文化气质。"},
        {"title_zh": "国际湿地公约大会：从若尔盖到潘塔纳尔的南北对话", "title_en": "Ramsar Convention Conference: Bridging Zoige and the Pantanal — A North-South Wetland Dialogue", "type": "impromptu_bridge", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际湿地保护政策制定者", "difficulty": 5, "knowledge_tags": '["nat_011"]', "scenario": "你在国际湿地公约大会上主持，巴西潘塔纳尔湿地的案例刚介绍完，接下来是中国若尔盖湿地。请用双语串场，对比世界上两个最大泥炭湿地的异同。"},

        # 历史文脉 - 更多即兴串场题
        {"title_zh": "金沙遗址博物馆之夜：从太阳神鸟到当代艺术", "title_en": "Jinsha Site Museum Night: From Sunbird to Contemporary Art", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "国际博物馆界与当代艺术家", "difficulty": 4, "knowledge_tags": '["hist_002"]', "scenario": "你主持'金沙遗址博物馆之夜'，上一个环节是太阳神鸟金饰的数字影像展示，下一个环节是当代艺术家以古蜀文明为灵感的现代舞表演。请用双语串场。"},
        {"title_zh": "中国诗歌节国际专场：从杜甫草堂到莎士比亚故居", "title_en": "China Poetry Festival International Session: From Du Fu's Thatched Cottage to Shakespeare's Birthplace", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "国际诗歌与文学界人士", "difficulty": 3, "knowledge_tags": '["hist_004"]', "scenario": "你在'杜甫与莎士比亚——跨文化的诗圣对话'主题活动上主持，刚读完一首杜甫诗的英文朗诵，接下来是莎士比亚十四行诗的中文演绎。请用双语串场。"},
        {"title_zh": "安岳大足国际石窟研讨会开幕式串场", "title_en": "Opening Bridge for the Anyue-Dazu International Cave Art Symposium", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "国际石窟艺术与文物保护专家", "difficulty": 4, "knowledge_tags": '["hist_006"]', "scenario": "你主持'安岳与大足——中国晚期石窟艺术的姊妹篇'国际研讨会，在安岳石刻的介绍视频和大足石刻的学术报告之间用双语串场。"},
        {"title_zh": "三国文化全球巡展成都站启动仪式串场", "title_en": "Three Kingdoms Culture Global Tour Chengdu Launch Ceremony Bridge", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "国际文博与动漫游戏产业界", "difficulty": 3, "knowledge_tags": '["hist_003"]', "scenario": "你主持'三国文化全球巡展'成都站启动仪式，在武侯祠博物馆馆长致辞和日本光荣公司《三国志》游戏40周年纪念环节之间用双语串场。"},
        {"title_zh": "中韩日三国'春节文化'联合申遗记者会串场", "title_en": "China-Korea-Japan 'Spring Festival Culture' Joint Heritage Nomination Press Conference Bridge", "type": "impromptu_bridge", "module": "history", "language_direction": "bilingual", "target_audience": "中韩日媒体与UNESCO官员", "difficulty": 5, "knowledge_tags": '["hist_005"]', "scenario": "在阆中举行的'春节文化'中韩日联合申遗记者会上，你用双语串场——阆中是'春节老人'落下闳的故乡，需要在中方发言和韩日代表发言之间建立文化共享的基调。"},

        # 非遗技艺 - 更多即兴串场题
        {"title_zh": "国际非遗节：蜀绣大师与法国高定设计师的对话串场", "title_en": "International ICH Festival: Bridging a Shu Embroidery Master and a French Haute Couture Designer", "type": "impromptu_bridge", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际时尚与传统工艺跨界人士", "difficulty": 4, "knowledge_tags": '["ich_002"]', "scenario": "在成都国际非遗节上，蜀绣国家级传承人刚展示完双面异色绣，接下来是一位法国高定设计师分享她将蜀绣融入时装系列的经验。请用双语串场。"},
        {"title_zh": "中国美食申遗国际论坛：川菜与法餐的味觉对话", "title_en": "China's Culinary Heritage Nomination International Forum: A Taste Dialogue Between Sichuan Cuisine and French Gastronomy", "type": "impromptu_bridge", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "UNESCO非遗官员与国际美食评论家", "difficulty": 4, "knowledge_tags": '["ich_003"]', "scenario": "你主持中国美食申遗国际论坛，法餐已入选UNESCO非遗，下一个演讲是川菜的24种味型。请用双语串场，对比两种'世界美食之都'（巴黎-成都）的味觉哲学。"},
        {"title_zh": "全球竹文化峰会：道明竹编与日本竹工艺的匠心对话", "title_en": "Global Bamboo Culture Summit: A Craftsmanship Dialogue Between Daoming Bamboo Weaving and Japanese Bamboo Art", "type": "impromptu_bridge", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际手工艺与可持续设计领域", "difficulty": 3, "knowledge_tags": '["ich_007"]', "scenario": "在全球竹文化峰会上，日本别府竹工艺的展示刚结束，接下来是成都道明竹编的'竹里'装置分享。请用双语串场，对比中日竹文化的审美差异与共通。"},
        {"title_zh": "国际灯彩艺术节：自贡灯会与里昂灯光节的跨文化串场", "title_en": "International Lantern Art Festival: Bridging Zigong Lantern Festival and Lyon Festival of Lights", "type": "impromptu_bridge", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际城市节庆与文旅产业界", "difficulty": 3, "knowledge_tags": '["ich_004"]', "scenario": "在自贡国际灯彩艺术节开幕式上，法国里昂灯光节的代表刚致辞完毕，接下来是自贡灯会的丝扎工艺展示。请用双语串场，让东西方'光之艺术'交相辉映。"},
        {"title_zh": "世界民族电影节：藏羌织绣纪录片首映礼串场", "title_en": "World Ethnographic Film Festival: Tibetan-Qiang Embroidery Documentary Premiere Bridge", "type": "impromptu_bridge", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际民族志电影与人类学界", "difficulty": 4, "knowledge_tags": '["ich_008"]', "scenario": "你主持世界民族电影节上关于藏羌织绣的纪录片首映礼，影片刚放映完毕，接下来是羌绣传承人和藏族氆氇织造传承人的现场演示。请用双语串场。"},

        # 城市与国际活动 - 即兴串场题
        {"title_zh": "成都大运会闭幕式：熊猫文化与国际青年之夜", "title_en": "Chengdu FISU Games Closing Ceremony: Panda Culture and the International Youth Night", "type": "impromptu_bridge", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "全球青年运动员与体育界人士", "difficulty": 3, "knowledge_tags": '["nat_001"]', "scenario": "成都大运会闭幕式上，意大利代表团刚表演完下一届东道主的节目，接下来是成都的熊猫主题告别演出。请用双语串场，传递青春友谊和大熊猫的和平寓意。"},
        {"title_zh": "成渝双城经济圈国际推介会：成都茶馆与重庆火锅的城市性格串场", "title_en": "Chengdu-Chongqing Economic Circle International Promotion: Bridging Chengdu Teahouse and Chongqing Hotpot — Two City Characters", "type": "impromptu_bridge", "module": "city_spirit", "language_direction": "bilingual", "target_audience": "国际投资与文化交流界", "difficulty": 3, "knowledge_tags": '["ich_003"]', "scenario": "你在成渝双城经济圈国际推介会上主持，成都代表刚介绍了公园城市建设，重庆代表即将介绍智能制造。请用双语串场，以'茶馆的慢'与'火锅的辣'为比喻衔接两座城市的气质。"},

        # 非遗技艺 - 跨文化评论题
        {"title_zh": "川剧变脸是'魔术'吗？为变脸的艺术本质正名", "title_en": "Is Sichuan Opera Face-Changing Just 'Magic'? Defending Its Artistic Essence", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际艺术节策展人", "difficulty": 3, "knowledge_tags": '["ich_001"]', "scenario": "在一场国际表演艺术节上，有西方策展人将变脸归类为'魔术表演'，请用英文发表评论，阐明变脸作为戏剧艺术而非魔术的本质。"},
        {"title_zh": "川菜只有'辣'吗？打破全球食客对川菜的刻板印象", "title_en": "Is Sichuan Cuisine Only About Spiciness? Breaking Global Stereotypes", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际美食评论家", "difficulty": 2, "knowledge_tags": '["ich_003"]', "scenario": "在国际美食文化论坛上，一位西方美食评论家说'川菜就是辣'，请用英文回应，介绍川菜24种味型的丰富性。"},
        {"title_zh": "自贡灯会：从中国元宵民俗到全球文化产业的蜕变", "title_en": "Zigong Lantern Festival: From Chinese Folk Custom to Global Cultural Industry", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "文化产业投资人与学者", "difficulty": 3, "knowledge_tags": '["ich_004"]', "scenario": "在'中国文化走出去'论坛上，用双语评述自贡灯会如何从一个地方民俗活动发展为年产值超50亿元的全球文化产业。"},

        # 非遗技艺 - 更多跨文化评论题
        {"title_zh": "三星堆是'外星文明'吗？回应西方媒体的考古误读", "title_en": "Is Sanxingdui an 'Alien Civilization'? Responding to Western Media's Archaeological Misreading", "type": "cross_cultural_commentary", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际媒体与科普界", "difficulty": 3, "knowledge_tags": '["hist_001"]', "scenario": "一家西方主流媒体在报道三星堆新发现时用了'外星文明'的标题。作为双语主持人和文化传播者，请用英文发表评论，纠正这一误导性叙事。"},
        {"title_zh": "大熊猫保护是'中国宣传工具'吗？", "title_en": "Is Giant Panda Conservation Just 'Chinese Propaganda'? A Fact-Based Response", "type": "cross_cultural_commentary", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际环保界与媒体", "difficulty": 4, "knowledge_tags": '["nat_001", "nat_006"]', "scenario": "有国际媒体质疑大熊猫保护是'中国的生态宣传工具'。请用英文回应，引用大熊猫从濒危降为易危的实际数据，论证中国保护工作的科学实质。"},
        {"title_zh": "都江堰是'落后技术'还是'超前智慧'？", "title_en": "Is Dujiangyan 'Backward Technology' or 'Ahead of Its Time'? A Philosophical Debate", "type": "cross_cultural_commentary", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际工程与可持续发展界", "difficulty": 4, "knowledge_tags": '["nat_008"]', "scenario": "一位西方工程师评论都江堰'只是一堆石头，没有技术含量'。请用英文回应，阐述都江堰'无坝引水'哲学对当代可持续水利工程的启示。"},
        {"title_zh": "中国'茶'变成英国'tea'：茶马古道与全球化之前的全球化", "title_en": "From Chinese 'Cha' to English 'Tea': The Tea Horse Road and Globalization Before Globalization", "type": "cross_cultural_commentary", "module": "history", "language_direction": "bilingual", "target_audience": "国际历史与全球化研究学者", "difficulty": 4, "knowledge_tags": '["hist_007"]', "scenario": "在一场关于'全球化历史'的国际研讨会上，有学者认为全球化始于大航海时代。请用双语评论茶马古道——一个早于大航海时代1300年的跨大陆贸易网络。"},
        {"title_zh": "彝族火把节是'落后迷信'还是'活态文化遗产'？", "title_en": "Is the Yi Torch Festival 'Backward Superstition' or 'Living Cultural Heritage'?", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际人类学与非遗保护界", "difficulty": 3, "knowledge_tags": '["ich_009"]', "scenario": "一位西方游客在社交媒体上称火把节是'原始的火崇拜迷信'。请用英文评论，从毕摩文化的哲学内涵和非遗保护的角度进行回应。"},
        {"title_zh": "竹编是'穷人材料'吗？回应西方对竹子建筑的文化偏见", "title_en": "Is Bamboo Weaving a 'Poor Man's Material'? Responding to Cultural Bias Against Bamboo Architecture", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际建筑与可持续设计界", "difficulty": 3, "knowledge_tags": '["ich_007"]', "scenario": "一位西方建筑师在论坛上称'竹子是第三世界的临时材料'。请用英文回应，以道明竹编'竹里'装置（威尼斯建筑双年展）为例，论述竹子作为未来建筑材料的价值。"},
        {"title_zh": "成都'茶馆文化'是'低效懒散'还是'生活智慧'？", "title_en": "Is Chengdu's Teahouse Culture 'Inefficient Laziness' or 'Life Wisdom'?", "type": "cross_cultural_commentary", "module": "city_spirit", "language_direction": "en_to_zh", "target_audience": "国际城市研究与生活质量学者", "difficulty": 3, "knowledge_tags": '[]', "scenario": "《纽约时报》一篇文章将成都茶馆文化描述为'一种与效率对立的慢生活'。请用英文评论，从成都连续多年被评为'中国最具幸福感城市'的角度回应。"},
        {"title_zh": "'天府之国'是自夸吗？为成都平原的文明地位辩护", "title_en": "Is 'Land of Abundance' Self-Praise? Defending the Civilizational Status of the Chengdu Plain", "type": "cross_cultural_commentary", "module": "history", "language_direction": "bilingual", "target_audience": "国际历史文化与农业文明学者", "difficulty": 4, "knowledge_tags": '["nat_008"]', "scenario": "一位外国学者说'中国只有黄河文明和长江文明，四川只是边缘'。请用双语评论，从三星堆、金沙遗址的考古证据出发，论证古蜀文明作为中华文明'多元一体'格局中重要一极的地位。"},
        {"title_zh": "藏羌织绣在国际时尚中使用算'文化挪用'吗？", "title_en": "Is Using Tibetan-Qiang Embroidery in International Fashion 'Cultural Appropriation'?", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际时尚伦理与文化研究界", "difficulty": 5, "knowledge_tags": '["ich_008"]', "scenario": "一个法国奢侈品牌使用了类似羌绣的几何图案但没有标注来源。你作为文化评论者，需要区分'文化挪用'与'文化交流'的边界。请用双语发表你的见解。"},
        {"title_zh": "阆中'春节发源地'的说法有依据吗？回应文化话语权的国际争议", "title_en": "Is Langzhong Really the 'Birthplace of Spring Festival'? Responding to International Debate on Cultural Authority", "type": "cross_cultural_commentary", "module": "history", "language_direction": "bilingual", "target_audience": "国际文化遗产与民俗学界", "difficulty": 4, "knowledge_tags": '["hist_005"]', "scenario": "韩国学者在民俗学会议上指出'春节并非任何单一城市的专属'。请用双语评论阆中自称'春节文化发源地'的依据——落下闳《太初历》将正月定为岁首的学术事实。"},
        {"title_zh": "川剧变脸的商业化是否背叛了其戏剧灵魂？", "title_en": "Has the Commercialization of Face-Changing Betrayed Its Theatrical Soul?", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际表演艺术与文化遗产界", "difficulty": 4, "knowledge_tags": '["ich_001"]', "scenario": "有戏剧评论家指出现在餐厅里表演的变脸'只是炫技，毫无剧情'。请用双语评论变脸从川剧舞台走向商业表演的利弊——是'非遗的堕落'还是'非遗的活态传承'？"},
        {"title_zh": "大熊猫为什么是黑白色的？从进化生物学到文化符号的跨学科解读", "title_en": "Why Are Giant Pandas Black and White? An Interdisciplinary Reading from Evolutionary Biology to Cultural Symbol", "type": "cross_cultural_commentary", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际科普与文化研究受众", "difficulty": 2, "knowledge_tags": '["nat_001"]', "scenario": "在一档国际科普节目中，主持人提出'大熊猫的黑白色有什么进化意义'。请用英文从生物学（伪装与社交信号）和文化象征（中国水墨画中的黑白美学）两个维度发表评论。"},
        {"title_zh": "蜀绣的'慢'与AI的'快'：手工的温度能否被算法取代？", "title_en": "The 'Slowness' of Shu Embroidery vs the 'Speed' of AI: Can the Warmth of Handwork Be Replaced by Algorithms?", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际科技与人文跨界受众", "difficulty": 4, "knowledge_tags": '["ich_002"]', "scenario": "硅谷一场TED演讲声称'AI将在十年内取代所有手工艺'。请用双语评论，以蜀绣122种针法的复杂性和'晕针'技法的不可编程性为例，辩论手工创造力的不可替代性。"},
        {"title_zh": "四川的'辣'与墨西哥的'辣'：全球辣椒文化的比较与对话", "title_en": "Sichuan 'Spicy' vs Mexican 'Spicy': A Comparative Dialogue on Global Chili Cultures", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际饮食文化研究者", "difficulty": 2, "knowledge_tags": '["ich_003"]', "scenario": "在国际美食文化节上，有墨西哥厨师评论'四川辣只是辣，没有层次'。请用双语回应，介绍花椒的'麻'与辣椒的'辣'——川菜麻辣味型的神经科学原理（羟基-α-山椒素引起的50Hz振动触觉）。"},
        {"title_zh": "'蜀道难'与'高铁快'：中国基建速度的文化代价是什么？", "title_en": "From 'Hard Roads to Shu' to High-Speed Rail: What Is the Cultural Cost of China's Infrastructure Speed?", "type": "cross_cultural_commentary", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际文化遗产保护与发展研究界", "difficulty": 5, "knowledge_tags": '["nat_005"]', "scenario": "BBC纪录片指出中国的高铁建设正在'吞噬古迹'。请用双语评论——以蜀道从千年古道到高铁走廊的变迁为例，讨论文化遗产保护与现代交通发展的平衡。"},
        {"title_zh": "青城山的'幽'与日本龙安寺的'寂'：东方美学的两种对话", "title_en": "The 'Seclusion' of Mount Qingcheng and the 'Wabi-sabi' of Ryoanji: Two Dialogues in Eastern Aesthetics", "type": "cross_cultural_commentary", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际美学与比较文化学者", "difficulty": 4, "knowledge_tags": '["nat_009"]', "scenario": "在一次中日美学对话论坛上，日本学者介绍了'侘寂'（wabi-sabi）。请用双语发表评论，将青城山的'幽'（seclusion/deep serenity）与'侘寂'进行比较对话。"},
        {"title_zh": "自贡恐龙博物馆：'中国侏罗纪公园'的科学叙事与娱乐化风险", "title_en": "Zigong Dinosaur Museum: The 'Chinese Jurassic Park' — Scientific Narrative vs Entertainment Risk", "type": "cross_cultural_commentary", "module": "history", "language_direction": "bilingual", "target_audience": "国际科普与博物馆学界", "difficulty": 3, "knowledge_tags": '["hist_010"]', "scenario": "有人提议将自贡恐龙博物馆改造成'中国侏罗纪公园'主题乐园。请用双语评论：恐龙科普传播中'科学性'与'娱乐性'的边界在哪里？"},
        {"title_zh": "米其林评星成都川菜：西方标准能否评判中国饮食？", "title_en": "Michelin Stars for Chengdu Sichuan Cuisine: Can Western Standards Judge Chinese Food?", "type": "cross_cultural_commentary", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际美食评论与文化研究界", "difficulty": 3, "knowledge_tags": '["ich_003"]', "scenario": "米其林指南首次进入成都，一家百年苍蝇馆子只得了一星，引发争议。请用双语评论：西方米其林标准是否适合评价有24种味型的川菜？"},

        # 综合 - 访谈应对题
        {"title_zh": "专访羌年非遗传承人", "title_en": "Interview with a Qiang New Year ICH Inheritor", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际非遗保护领域观众", "difficulty": 4, "knowledge_tags": '["ich_005"]', "scenario": "你主持一档国际非遗人物专访，嘉宾是一位经历过汶川地震的羌年释比（祭司）传承人。用双语进行采访，探索羌族文化在灾难后的重生故事。"},
        {"title_zh": "对话在成都创作的美国爵士音乐家", "title_en": "Interview with an American Jazz Musician Creating in Chengdu", "type": "interview", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际文化交流爱好者", "difficulty": 3, "knowledge_tags": '[]', "scenario": "一位美国爵士音乐家在成都生活了5年，将川剧元素融入爵士乐创作。作为双语主持人，对他进行采访，探讨文化融合的创作体验。"},

        # 综合 - 更多访谈应对题
        {"title_zh": "专访三星堆考古队长：新祭祀坑发现背后的故事", "title_en": "Interview with the Sanxingdui Archaeology Team Leader: Stories Behind the New Sacrificial Pit Discoveries", "type": "interview", "module": "history", "language_direction": "bilingual", "target_audience": "国际考古与文化爱好者", "difficulty": 4, "knowledge_tags": '["hist_001"]', "scenario": "你主持一档国际考古人物专访，嘉宾是三星堆新祭祀坑发掘的考古队长。用双语采访，围绕2020-2023年6个新坑的发现过程、象牙提取的技术挑战和古蜀文明未解之谜展开。"},
        {"title_zh": "对话蜀绣国家级传承人：一根针的千年传承与当代创新", "title_en": "Dialogue with a National Shu Embroidery Inheritor: A Thousand-Year Legacy and Contemporary Innovation in One Needle", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际手工艺与文化创意产业观众", "difficulty": 3, "knowledge_tags": '["ich_002"]', "scenario": "你主持国际手工艺大师访谈，嘉宾是蜀绣国家级传承人郝淑萍。用双语采访她如何从12岁学艺到将蜀绣带入国际时尚舞台，以及'晕针'技法的奥秘。"},
        {"title_zh": "与在自贡研究恐龙化石的法国古生物学家对话", "title_en": "A Dialogue with a French Paleontologist Studying Dinosaur Fossils in Zigong", "type": "interview", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际科学传播受众", "difficulty": 3, "knowledge_tags": '["hist_010"]', "scenario": "你采访一位在自贡大山铺工作了15年的法国古生物学家。用英文探讨：为什么自贡的侏罗纪化石群在全球独一无二？中法古生物合作带来了哪些突破？"},
        {"title_zh": "专访彝族毕摩：火把节背后的信仰世界", "title_en": "Interview with a Yi Bimo Priest: The Spiritual World Behind the Torch Festival", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际人类学与宗教学受众", "difficulty": 4, "knowledge_tags": '["ich_009"]', "scenario": "你深入凉山彝区，专访一位毕摩（彝族祭司），用双语探讨火把节的宗教意涵、毕摩经书的传承困境和年轻一代对传统信仰的态度变化。"},
        {"title_zh": "对话将都江堰写入世界水利教科书的剑桥学者", "title_en": "A Conversation with the Cambridge Scholar Who Put Dujiangyan in the World's Water Engineering Textbook", "type": "interview", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际工程教育与科技史受众", "difficulty": 3, "knowledge_tags": '["nat_008"]', "scenario": "你采访一位将都江堰纳入剑桥大学水利工程教材的英国学者。用英文探讨：一个2280年前的无坝工程在现代水力学视角下究竟'先进'在哪里？"},
        {"title_zh": "专访道明竹编传承人与建筑师刘家琨", "title_en": "Interview with a Daoming Bamboo Weaving Inheritor and Architect Liu Jiakun", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际建筑与设计界", "difficulty": 4, "knowledge_tags": '["ich_007"]', "scenario": "你同时采访道明竹编传承人和'竹里'装置建筑师刘家琨，用双语探讨传统手工艺与当代建筑的合作——竹编如何从日用器物走向威尼斯建筑双年展。"},
        {"title_zh": "与在成都养熊猫的美国动物行为学家对话", "title_en": "A Conversation with an American Animal Behaviorist Raising Pandas in Chengdu", "type": "interview", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际野生动物保护与科普受众", "difficulty": 2, "knowledge_tags": '["nat_001"]', "scenario": "你采访一位在成都大熊猫基地工作了10年的美国动物行为学家。用英文探讨：大熊猫的行为研究如何改变了圈养繁殖策略？她如何看待'熊猫外交'的争议？"},
        {"title_zh": "专访阆中'春节老人'落下闳的后人与民俗学者", "title_en": "Interview with Descendants of Langzhong's 'Spring Festival Elder' Luo Xiahong and a Folklorist", "type": "interview", "module": "history", "language_direction": "bilingual", "target_audience": "国际民俗与天文史爱好者", "difficulty": 3, "knowledge_tags": '["hist_005"]', "scenario": "你采访落下闳的后人和研究《太初历》的民俗学者，用双语探讨：2000年前一位四川天文学家如何确定了'春节'的日期？阆中为何被称为'春节文化发源地'？"},
        {"title_zh": "对话自贡灯会'出海'项目负责人", "title_en": "Dialogue with the Head of Zigong Lantern Festival's Global Expansion", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际文化产业与文旅从业者", "difficulty": 3, "knowledge_tags": '["ich_004"]', "scenario": "你采访自贡灯会海外项目的总负责人，用双语探讨自贡灯会如何打入80多个国家的市场——从设计、制作到运营的完整产业链，以及跨文化适应的挑战。"},
        {"title_zh": "专访九寨沟震后生态修复项目首席科学家", "title_en": "Interview with the Chief Scientist of Jiuzhaigou's Post-Earthquake Ecological Restoration", "type": "interview", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际生态修复与地质学界", "difficulty": 4, "knowledge_tags": '["nat_002"]', "scenario": "你采访负责九寨沟震后修复的首席科学家，用英文探讨：7.0级地震如何改变了一个世界自然遗产？自然修复和人工干预的边界在哪里？九寨沟的经验对全球灾害遗产保护有何启示？"},
        {"title_zh": "对话在成都学川剧变脸的非洲留学生", "title_en": "A Dialogue with an African Student Learning Face-Changing at a Chengdu Sichuan Opera School", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际文化交流与教育界", "difficulty": 2, "knowledge_tags": '["ich_001"]', "scenario": "你采访一位在成都川剧学校学习变脸的坦桑尼亚留学生。用双语探讨：一个非洲人为何对变脸着迷？'传内不传外'的传统对他有影响吗？他如何理解变脸不是魔术而是戏剧？"},
        {"title_zh": "专访致力于蜀道申遗的国际古迹遗址理事会专家", "title_en": "Interview with an ICOMOS Expert Working on the Shu Roads World Heritage Nomination", "type": "interview", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际文化遗产保护专业观众", "difficulty": 4, "knowledge_tags": '["nat_005"]', "scenario": "你采访一位为蜀道申遗工作的ICOMOS（国际古迹遗址理事会）专家，用双语探讨蜀道作为'线性文化遗产'的突出普遍价值（OUV），以及与罗马古道、印加之路的跨国比较。"},
        {"title_zh": "与若尔盖湿地黑颈鹤保护志愿者对话", "title_en": "Dialogue with Black-Necked Crane Conservation Volunteers at Zoige Wetlands", "type": "interview", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际生态保护与志愿者文化受众", "difficulty": 2, "knowledge_tags": '["nat_011"]', "scenario": "你采访一群在若尔盖湿地做黑颈鹤保护的藏族志愿者，用双语探讨当地社区如何从'湿地使用者'转变为'湿地守护者'，以及藏传佛教中的护生理念如何促进现代生态保护。"},
        {"title_zh": "专访将羌绣带上巴黎时装周的独立设计师", "title_en": "Interview with the Independent Designer Who Brought Qiang Embroidery to Paris Fashion Week", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际时尚与文化创意产业界", "difficulty": 3, "knowledge_tags": '["ich_008"]', "scenario": "你采访一位将羌绣元素融入高级时装并在巴黎时装周展出的独立设计师，用双语探讨：传统民族工艺进入国际时尚体系时，如何解决'文化借用'与'文化尊重'的边界问题？"},
        {"title_zh": "对话在安岳石刻做数字化保护的德国团队", "title_en": "Dialogue with a German Team Doing Digital Conservation at Anyue Stone Carvings", "type": "interview", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际文物保护与科技跨界受众", "difficulty": 4, "knowledge_tags": '["hist_006"]', "scenario": "你采访一个在安岳用3D扫描技术记录石刻的德国文物保护团队，用英文探讨：安岳石刻因分散在乡野而面临保护难题——数字化是解药吗？散落在田野的国宝如何获得国际关注？"},
        {"title_zh": "专访成都漆艺'金银平脱'技艺的唯一传承人", "title_en": "Interview with the Last Inheritor of Chengdu Lacquer Art's 'Gold-Silver Inlay' Technique", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际工艺美术与文化遗产保护界", "difficulty": 4, "knowledge_tags": '["ich_010"]', "scenario": "你采访掌握成都漆艺'金银平脱'技法的最后一位传承人，用双语探讨这门汉代巅峰技艺为何濒临失传——一件精品需耗时一年，在'快消费'时代如何找到传承人？"},
        {"title_zh": "专访将杜甫诗歌译成英文的剑桥汉学家", "title_en": "Interview with the Cambridge Sinologist Who Translates Du Fu's Poetry into English", "type": "interview", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际文学与翻译界", "difficulty": 3, "knowledge_tags": '["hist_004"]', "scenario": "你采访一位用30年将杜甫全部1400首诗译成英文的剑桥汉学家，用英文探讨：杜诗中的'诗史'精神如何在英文中传达？西方读者为何称杜甫为'中国的莎士比亚'？"},
        {"title_zh": "对话在四姑娘山训练的国际登山向导", "title_en": "Dialogue with an International Mountain Guide Training at Mount Siguniang", "type": "interview", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际户外探险与极限运动受众", "difficulty": 2, "knowledge_tags": '["nat_014"]', "scenario": "你采访一位每年都来四姑娘山幺妹峰训练的国际登山向导，用英文探讨：为什么'蜀山之后'在全球登山界享有崇高地位？登山者如何看待当地藏族的'神山不可登'信仰？"},

        # 综合 - 危机救场题
        {"title_zh": "大熊猫基地直播中翻译设备故障", "title_en": "Translation Equipment Failure During Panda Base Live Stream", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "全球直播观众", "difficulty": 4, "knowledge_tags": '["nat_001"]', "scenario": "你在成都大熊猫基地进行全球直播，突然翻译设备故障，国际观众的英文同传中断。在技术人员修复期间（2分钟），你需要用英文向国际观众独立解说大熊猫的日常生活。"},
        {"title_zh": "三星堆国际学术研讨会上的敏感提问", "title_en": "Handling a Sensitive Question at the Sanxingdui International Symposium", "type": "crisis_rescue", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际考古学界", "difficulty": 5, "knowledge_tags": '["hist_001"]', "scenario": "在三星堆国际学术研讨会上，一位外国学者提问：'三星堆文明是否可能源自西亚而非中华本土？'作为双语主持人，你需要专业而体面地回应这个敏感的学术争议。"},

        # 综合 - 更多危机救场题
        {"title_zh": "自贡灯会开幕式突发停电", "title_en": "Sudden Blackout at Zigong Lantern Festival Opening Ceremony", "type": "crisis_rescue", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "现场国际观众与直播观众", "difficulty": 4, "knowledge_tags": '["ich_004"]', "scenario": "自贡国际恐龙灯会开幕式上，所有灯组突然断电，全场一片漆黑。作为双语主持人，你需要在技术人员抢修（预计3分钟）时，用中英双语稳住现场观众和国际直播观众。"},
        {"title_zh": "九寨沟国际生态论坛上外国专家突然质疑中国环保数据", "title_en": "Foreign Expert Suddenly Questions China's Environmental Data at Jiuzhaigou International Ecology Forum", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际环保界与媒体", "difficulty": 5, "knowledge_tags": '["nat_002"]', "scenario": "在九寨沟国际生态恢复论坛上，一位外国生态学家突然质疑中国官方发布的震后恢复数据'过于乐观'。作为双语主持人，你需要用英文立刻回应——既要维护会议氛围，又要展现开放对话的态度。"},
        {"title_zh": "成都大运会开幕式：同传耳机频道全部串音", "title_en": "Chengdu FISU Games Opening Ceremony: All Simultaneous Interpretation Channels Cross-Talking", "type": "crisis_rescue", "module": "city_spirit", "language_direction": "bilingual", "target_audience": "全球直播观众与现场数万名运动员", "difficulty": 5, "knowledge_tags": '[]', "scenario": "成都大运会开幕式直播中，国际观众的同传耳机突然串音——法语频道听到的是中文，英语频道听到的是韩语。作为双语主持人，你需要在技术修复的5分钟内，用中英双语向全球观众临时解说正在进行的巴蜀文化表演。"},
        {"title_zh": "川菜品鉴会上外国使节被花椒呛到", "title_en": "Foreign Diplomat Chokes on Sichuan Pepper at a Sichuan Cuisine Tasting Event", "type": "crisis_rescue", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "各国外交官与国际媒体", "difficulty": 3, "knowledge_tags": '["ich_003"]', "scenario": "在一次国际川菜品鉴会上，一位欧洲驻华使节误吞了一整颗花椒，当场剧烈咳嗽。作为双语主持人，你需要用幽默化解尴尬气氛，同时不失时机地向国际嘉宾讲解花椒'麻'的科学原理。"},
        {"title_zh": "武侯祠国际文化节上日本和韩国嘉宾因三国历史争议僵持", "title_en": "Japanese and Korean Guests Clash Over Three Kingdoms History at Wuhou Shrine International Festival", "type": "crisis_rescue", "module": "history", "language_direction": "bilingual", "target_audience": "中日韩文化界与媒体", "difficulty": 5, "knowledge_tags": '["hist_003"]', "scenario": "在武侯祠国际三国文化节上，日本嘉宾提到'三国文化在日本更受欢迎'，韩国嘉宾立即反驳'韩国也有自己的三国史观'。作为双语主持人，你需要立刻用双语调解，将焦点拉回三国文化作为东亚共同文化遗产的正题。"},
        {"title_zh": "蜀道徒步活动中外国记者扭伤脚踝", "title_en": "Foreign Journalist Sprains Ankle During Shu Roads Hiking Event", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "随行国际媒体团", "difficulty": 3, "knowledge_tags": '["nat_005"]', "scenario": "在蜀道翠云廊的国际媒体徒步体验中，一位BBC记者不慎扭伤脚踝。作为双语主持人，你需要协调救援的同时，用中英双语将这场'小意外'自然地融入对蜀道之'险'的历史叙事中——'正如李白所言，蜀道之难，今天我们也亲身体验了'。"},
        {"title_zh": "大熊猫命名仪式上幼崽突然跑下舞台", "title_en": "Panda Cub Runs Off Stage During Naming Ceremony", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "全球直播观众与现场嘉宾", "difficulty": 2, "knowledge_tags": '["nat_001"]', "scenario": "在成都大熊猫基地的新生幼崽全球征名揭晓仪式直播中，幼崽突然从保育员怀里挣脱跑下了舞台。作为双语主持人，用中英双语把这场'小事故'变成大熊猫可爱天性的最好展示。"},
        {"title_zh": "国际非遗节上蜀绣作品被展示架砸坏", "title_en": "Shu Embroidery Artwork Damaged by Falling Display Stand at International ICH Festival", "type": "crisis_rescue", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "现场观众与非遗传承人", "difficulty": 4, "knowledge_tags": '["ich_002"]', "scenario": "在国际非遗节蜀绣展厅，一个展示架突然倾倒，一件耗时三年的蜀绣精品被轻微损坏。蜀绣传承人当场落泪。作为双语主持人，你需要用中英双语处理——先安抚传承人，再向国际观众用语言'修复'这件作品的魅力。"},
        {"title_zh": "都江堰放水节直播中突降暴雨", "title_en": "Sudden Heavy Rain During Dujiangyan Water-Releasing Festival Live Broadcast", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "全球直播观众", "difficulty": 3, "knowledge_tags": '["nat_008"]', "scenario": "都江堰放水节全球直播中突降暴雨，所有表演被迫暂停。作为双语主持人，用中英双语把暴雨'接住'——这是两千年来都江堰最熟悉的天气，正好让观众理解为什么古人要建造这个伟大的水利工程。"},
        {"title_zh": "国际古蜀文明研讨会上中国与埃及学者发生考古优先权争议", "title_en": "Chinese and Egyptian Scholars Clash Over Archaeological Primacy at International Ancient Shu Symposium", "type": "crisis_rescue", "module": "history", "language_direction": "en_to_zh", "target_audience": "国际考古学界与媒体", "difficulty": 5, "knowledge_tags": '["hist_001", "hist_002"]', "scenario": "在三星堆-金沙国际研讨会上，一位埃及学者说'三星堆没什么了不起，比金字塔晚了两千年'。中国学者面色不悦。作为双语主持人，用英文迅速回应——强调文明比较不应是'谁更古老'的竞赛，而是各自对人类文明的独特贡献。"},
        {"title_zh": "海螺沟冰川考察中外国科学家发现冰川消融远超预期", "title_en": "Foreign Scientist Finds Glacial Melt Far Exceeding Expectations During Hailuogou Expedition", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "随行国际科学家与气候媒体", "difficulty": 4, "knowledge_tags": '["nat_012"]', "scenario": "在海螺沟冰川国际联合考察中，一位美国冰川学家突然高声宣布：'冰川消融速度比五年前快了40%！'现场记者纷纷举起相机。作为双语主持人，用英文将这个'坏消息'转化为全球气候行动的紧迫呼吁。"},
        {"title_zh": "茶马古道文化展开幕式上藏茶品鉴环节被质疑'文化表演化'", "title_en": "Tibetan Tea Tasting at Tea Horse Road Exhibition Opening Accused of 'Cultural Performativity'", "type": "crisis_rescue", "module": "history", "language_direction": "bilingual", "target_audience": "国际文化研究与媒体界", "difficulty": 4, "knowledge_tags": '["hist_007"]', "scenario": "在茶马古道国际文化展开幕式上，一位人类学家突然举手质疑：'你们现在展示的藏茶仪式只是为游客设计的'表演'，不是真实的茶马古道文化。'作为双语主持人，你需要用真诚回应——承认商业化的现实，但更要讲好这条千年古道上真实的汉藏交流故事。"},
        {"title_zh": "剑门关国际军事史年会上投影设备故障", "title_en": "Projector Failure at Jianmen Pass International Military History Conference", "type": "crisis_rescue", "module": "history", "language_direction": "bilingual", "target_audience": "国际军事历史学者", "difficulty": 3, "knowledge_tags": '["hist_008"]', "scenario": "在剑门关国际军事史年会现场，投影仪突然故障，下一个演讲者关于'古代关隘防御体系'的PPT无法展示。作为双语主持人，用中英双语即兴引导观众：'不如我们看向窗外的剑门七十二峰——这就是最好的PPT，诸葛亮一千八百年前已经为我们准备好了。'"},
        {"title_zh": "全球竹文化峰会直播中翻译把'竹编'误译为'bamboo knitting'", "title_en": "Interpreter At Global Bamboo Culture Summit Mistranslates 'Bamboo Weaving' as 'Bamboo Knitting'", "type": "crisis_rescue", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际手工艺与设计界", "difficulty": 3, "knowledge_tags": '["ich_007"]', "scenario": "在全球竹文化峰会直播中，同传译员将'竹编'（bamboo weaving）错误地译为'bamboo knitting'（竹子针织）。作为双语主持人，你听到后需要在不尴尬同传的情况下，自然地在串场中纠正并解释正确的术语。"},
        {"title_zh": "峨眉山国际佛学论坛上素食宴会出现荤食混入", "title_en": "Meat Found in Vegetarian Banquet at Mount Emei International Buddhist Forum", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际宗教界人士", "difficulty": 5, "knowledge_tags": '["nat_004"]', "scenario": "在峨眉山国际佛学论坛的素食宴会上，一位泰国僧人在菜中发现肉末。场面一度凝重。作为双语主持人，你需要协助主办方道歉的同时，用中英双语将话题引导到'饮食禁忌的跨文化理解'这一建设性方向。"},
        {"title_zh": "国际道教文化节上美国游客误入道士闭关区", "title_en": "American Tourist Accidentally Enters Taoist Monk's Seclusion Area During International Taoist Festival", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际游客与道教界人士", "difficulty": 3, "knowledge_tags": '["nat_009"]', "scenario": "在青城山国际道教文化节上，一位美国游客因看不懂中文警示牌，误入道士闭关修行的禁地，被守卫严厉呵斥。作为双语主持人，用英文向游客解释'闭关'的文化含义，同时向道士转达游客的歉意和无知。"},
        {"title_zh": "若尔盖湿地论坛上卫星图显示草场退化引发牧民代表抗议", "title_en": "Satellite Image of Grassland Degradation Sparks Herder Protest at Zoige Wetland Forum", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际生态保护界与当地社区", "difficulty": 5, "knowledge_tags": '["nat_011"]', "scenario": "在若尔盖国际湿地保护论坛上，一位外国科学家展示了若尔盖草场退化的大尺度卫星对比图。在场的藏族牧民代表激动地站起来抗议：'我们的生活方式不是生态问题！'作为双语主持人，用中英双语化解这一'科学数据'与'在地知识'的对立。"},
        {"title_zh": "西昌卫星发射中心国际观摩活动中发射倒计时突然暂停", "title_en": "Launch Countdown Suddenly Pauses During International Observation Event at Xichang Satellite Launch Center", "type": "crisis_rescue", "module": "natural_heritage", "language_direction": "bilingual", "target_audience": "国际航天界人士与全球媒体", "difficulty": 4, "knowledge_tags": '["nat_015"]', "scenario": "在西昌卫星发射中心国际观摩活动中，发射倒计时至T-30秒时突然宣布暂停。现场来自20个国家的观摩团一片哗然。作为双语主持人，用中英双语在技术原因不明的2分钟内控场，将话题转向航天发射中'安全优先'的普世原则。"},
        {"title_zh": "安岳石刻考察中无人机坠入唐代摩崖造像区", "title_en": "Drone Crashes Into Tang Dynasty Cliff Sculpture Area During Anyue Stone Carvings Inspection", "type": "crisis_rescue", "module": "history", "language_direction": "bilingual", "target_audience": "国际文物保护专家与媒体", "difficulty": 4, "knowledge_tags": '["hist_006"]', "scenario": "在安岳石刻国际专家考察中，一位外国记者的航拍无人机失控坠入千年摩崖造像群。现场文物管理员愤怒上前，记者显得不知所措。作为双语主持人，用中英双语调解——先检查文物安全，再向国际团队解释中国'田野文物'保护的困境与焦虑。"},

        # 综合 - 更多观点辩论题
        {"title_zh": "双语主持中文化'归化'与'异化'的策略选择", "title_en": "Cultural 'Domestication' vs 'Foreignization' Strategy in Bilingual Hosting", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际翻译与跨文化传播学界", "difficulty": 4, "knowledge_tags": '[]', "scenario": "在一场国际跨文化传播辩论赛上，正方的观点是'跨文化主持应该尽量让外国受众感到'熟悉'（归化策略，如都江堰类比罗马水道）'，你持反方观点——'保留文化陌生感更有价值（异化策略，让国际受众真正接触异质文化）'。请用双语论述。"},
        {"title_zh": "AI翻译能否取代双语主持人？", "title_en": "Can AI Translation Replace Bilingual Hosts?", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际传播与AI技术跨界受众", "difficulty": 3, "knowledge_tags": '[]', "scenario": "在一场'AI vs 人文'的辩论赛中，正方说：'GPT实时翻译已经比大多数双语主持人更准确。'你持反方——'AI永远无法替代双语主持人的文化判断力和临场温度'。请用双语论证。"},
        {"title_zh": "三星堆文物应该全球巡展还是'原地不动'？", "title_en": "Should Sanxingdui Artifacts Go on Global Tour or Stay in Place?", "type": "debate", "module": "history", "language_direction": "bilingual", "target_audience": "国际文化遗产与博物馆界", "difficulty": 4, "knowledge_tags": '["hist_001"]', "scenario": "在国际博物馆伦理辩论会上，有人说'三星堆文物应该像图坦卡蒙一样全球巡展'，另一方说'文物离开原生语境就是失根的展示'。你持'有条件的全球巡展'的中间立场，用双语论证。"},
        {"title_zh": "大熊猫应该从濒危名录中'毕业'吗？", "title_en": "Should Giant Pandas 'Graduate' from the Endangered Species List?", "type": "debate", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际生态保护政策制定者", "difficulty": 4, "knowledge_tags": '["nat_001", "nat_006"]', "scenario": "在国际自然保护联盟（IUCN）辩论会上，有专家说'大熊猫降级为易危意味着保护资源应该转移给更需要钱的物种'。你持反对意见——'大熊猫作为伞护种和全球保护标志，不能仅按数字决策'。请用英文论证。"},
        {"title_zh": "自贡灯会应该保持传统手工还是全面拥抱LED和AI？", "title_en": "Should Zigong Lantern Festival Preserve Traditional Handcraft or Fully Embrace LED and AI?", "type": "debate", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际文化产业与技术跨界人士", "difficulty": 3, "knowledge_tags": '["ich_004"]', "scenario": "在'非遗的科技化'辩论中，有人说'灯光节本来就是灯的艺术，为什么不全部用最新的LED和AI技术？'你持'传统丝扎工艺不可被替代'的立场，用双语论证——手工的温度正是自贡灯会区别于其他灯光秀的核心竞争力。"},
        {"title_zh": "巴蜀文化国际传播应该主打'熊猫牌'还是'三星堆牌'？", "title_en": "Should the International Promotion of Ba-Shu Culture Lead with 'Panda' or 'Sanxingdui'?", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际文化传播与城市品牌专家", "difficulty": 3, "knowledge_tags": '["nat_001", "hist_001"]', "scenario": "在四川国际传播策略研讨会上，有人说'熊猫是四川最有全球辨识度的IP，应该all in熊猫'，有人说'老是熊猫太低幼了，三星堆才是最独特的文化符号'。你持'双IP战略'的中立立场，用双语论证。"},
        {"title_zh": "川菜入遗应该强调'正宗性'还是'创新性'？", "title_en": "Should Sichuan Cuisine's UNESCO Bid Emphasize 'Authenticity' or 'Innovation'?", "type": "debate", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "UNESCO非遗官员与全球美食界", "difficulty": 4, "knowledge_tags": '["ich_003"]', "scenario": "在川菜申报UNESCO非遗的讨论会上，有人说'必须回到最传统的配方才能申遗'，有人说'川菜本来就是不断融合创新的结果，不能固化'。你持'活态传承'立场——核心技艺不变，表达形式可以进化。用双语论述。"},
        {"title_zh": "中国国家公园应该像美国一样完全禁止人类居住吗？", "title_en": "Should Chinese National Parks Completely Ban Human Habitation Like American Ones?", "type": "debate", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际保护地管理政策制定者", "difficulty": 5, "knowledge_tags": '["nat_006"]', "scenario": "在国际国家公园管理辩论会上，一位美国专家说：'真正的国家公园就应该像黄石一样，把人都迁出去。'你持'中国特色国家公园'立场——大熊猫国家公园内仍有原住民社区，人与自然的共生不应被切断。请用英文论证。"},
        {"title_zh": "三国文化不是'历史'而是'IP'——文学改编的边界在哪里？", "title_en": "Is Three Kingdoms Culture Not 'History' but 'IP'? Where Is the Boundary of Literary Adaptation?", "type": "debate", "module": "history", "language_direction": "bilingual", "target_audience": "国际历史学界与流行文化创作者", "difficulty": 3, "knowledge_tags": '["hist_003"]', "scenario": "在一场'历史vs娱乐'的辩论中，有人说'三国演义70%是虚构，本质上和漫威宇宙没什么区别'。你持'历史文学有其独特的文化传承价值'的立场，用双语反驳——削弱三国IP的历史厚度，就失去了它最核心的魅力。"},
        {"title_zh": "巴蜀文化国际传播中应该去'中国化'还是强调'中国性'？", "title_en": "Should Ba-Shu Culture's International Communication De-emphasize or Emphasize Its 'Chineseness'?", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际传播战略研究者", "difficulty": 5, "knowledge_tags": '[]', "scenario": "在一场国际传播战略辩论中，有人说'文化走出去应该弱化政治标签，强调地方性而非国家性更容易被接受'。你持'地方性与国家性不是对立而是互嵌'的立场——巴蜀文化既是地方的也是中国的，不应切割。用双语论述。"},
        {"title_zh": "将非遗传承人'明星化'有助于保护还是加速异化？", "title_en": "Does Turning ICH Inheritors into 'Stars' Help Preservation or Accelerate Alienation?", "type": "debate", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "国际非遗保护与文化政策界", "difficulty": 4, "knowledge_tags": '["ich_001", "ich_002"]', "scenario": "在非遗保护国际研讨会上，有人说'应该把传承人打造成文化明星才有流量'，有人说'一旦成为明星就不再是真正的传承人了'。你持'有节制的公众化'的中立立场，用双语论述。"},
        {"title_zh": "旅游开发是'保护'还是'破坏'巴蜀文化遗产？", "title_en": "Is Tourism Development 'Protecting' or 'Destroying' Ba-Shu Cultural Heritage?", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际文化遗产与旅游管理界", "difficulty": 3, "knowledge_tags": '[]', "scenario": "在一场文化旅游辩论中，反方说'九寨沟每天限流就是承认旅游是破坏'，你持'负责任旅游可以实现保护与发展双赢'的立场，用双语列举巴蜀地区的正面案例论证。"},
        {"title_zh": "成都的'安逸'是否是城市国际竞争力的'绊脚石'？", "title_en": "Is Chengdu's 'Ease and Comfort' a 'Stumbling Block' to Its International Competitiveness?", "type": "debate", "module": "city_spirit", "language_direction": "en_to_zh", "target_audience": "国际城市竞争力研究学者", "difficulty": 3, "knowledge_tags": '[]', "scenario": "在世界城市竞争力论坛的辩论环节，有人说'成都太安逸了，缺乏深圳那样的狼性文化，不利于国际化'。你持'生活品质本身就是城市竞争力'的反方立场，用英文论证——全球人才争夺战中，宜居性正在成为关键变量。"},
        {"title_zh": "竹编建筑的全球推广算'文化输出'还是'生态方案共享'？", "title_en": "Is the Global Promotion of Bamboo-Weaving Architecture 'Cultural Export' or 'Ecological Solution Sharing'?", "type": "debate", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际可持续建筑与文化研究界", "difficulty": 4, "knowledge_tags": '["ich_007"]', "scenario": "在国际绿色建筑论坛上，有人质疑'中国的竹建筑推广不过是文化输出'。你持不同观点——竹子作为一种负碳建筑材料，其推广首先是对全球气候危机的回应，文化归属是次要问题。用英文论证。"},
        {"title_zh": "中国世界遗产数量全球第二是'文化遗产大国'还是'申遗功利主义'？", "title_en": "Is China's Second-Most World Heritage Sites a Sign of 'Cultural Power' or 'Heritage Utilitarianism'?", "type": "debate", "module": "history", "language_direction": "bilingual", "target_audience": "国际文化遗产政策专家", "difficulty": 5, "knowledge_tags": '["hist_005"]', "scenario": "在国际文化遗产辩论会上，有学者批评中国申遗是'数量竞赛'而非真正保护。你持'中国遗产数量多是因为文明延续五千年未断、地域辽阔多样'的立场，以巴蜀地区遗产为例用双语辩护。"},

        # 综合 - 更多观点辩论题（续）
        {"title_zh": "巴蜀文化国际传播中，'萌熊猫'路线是否拉低了文化深度？", "title_en": "Does the 'Cute Panda' Approach in Ba-Shu Cultural Communication Undermine Cultural Depth?", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际文化传播与公共外交学者", "difficulty": 3, "knowledge_tags": '["nat_001"]', "scenario": "在'国家文化品牌的通俗化'辩论中，有人说'老是拿熊猫卖萌，谁还记得三星堆和都江堰？'你持'通俗IP是深度文化的入口'的立场——先用熊猫把世界引进来，再用内容让世界留下来。用双语论述。"},

        # 综合 - 观点辩论题
        {"title_zh": "成都的快速现代化是否威胁了其传统文化认同？", "title_en": "Is Chengdu's Rapid Modernization Threatening Its Traditional Cultural Identity?", "type": "debate", "module": "city_spirit", "language_direction": "bilingual", "target_audience": "国际城市规划与文化保护领域观众", "difficulty": 4, "knowledge_tags": '[]', "scenario": "在一场国际城市发展论坛的辩论环节，你持'现代化与传统文化可以共生'的立场，用双语发表观点。"},
        {"title_zh": "大熊猫外交：保护合作还是政治工具？", "title_en": "Panda Diplomacy: Conservation Cooperation or Political Tool?", "type": "debate", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际关系与生态保护学者", "difficulty": 5, "knowledge_tags": '["nat_001", "nat_006"]', "scenario": "在国际关系的课堂辩论中，有观点认为中国的大熊猫外交本质上是政治工具。请用英文回应，论证大熊猫保护合作的科学价值和全球生态意义。"},
        {"title_zh": "蜀绣等传统手工艺在数字化时代还有价值吗？", "title_en": "Do Traditional Crafts Like Shu Embroidery Still Hold Value in the Digital Age?", "type": "debate", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际设计与文创产业界", "difficulty": 3, "knowledge_tags": '["ich_002", "ich_006", "ich_007"]', "scenario": "在一场'传统vs数字'的国际文创辩论赛中，用英文论述蜀绣、竹编等传统手工艺在当代的不可替代价值。"},
        {"title_zh": "茶马古道 vs 丝绸之路：谁对文明交流贡献更大？", "title_en": "Tea Horse Road vs Silk Road: Which Contributed More to Civilizational Exchange?", "type": "debate", "module": "history", "language_direction": "bilingual", "target_audience": "国际历史文化学者", "difficulty": 5, "knowledge_tags": '["hist_007"]', "scenario": "在一场国际历史地理学研讨会上，用中英双语论证茶马古道在汉藏文化交流和中华民族共同体形成中的独特价值——它不应只是丝绸之路的'注脚'。"},

        # ==========================================================
        # 入门级题目（难度1星）：适合初学者基础练习
        # ==========================================================

        # 入门 - 文化解说题
        {"title_zh": "用三个关键词向外国朋友介绍成都", "title_en": "Introduce Chengdu to a Foreign Friend in Three Keywords", "type": "cultural_explanation", "module": "city_spirit", "language_direction": "en_to_zh", "target_audience": "初次来华的普通外国人", "difficulty": 1, "knowledge_tags": '[]', "scenario": "你第一次见到一位刚来成都的外国朋友，他问'成都是什么样的城市？'请用英文，选三个关键词来介绍成都。"},
        {"title_zh": "向外国同学解释'大熊猫不只是可爱的动物'", "title_en": "Explaining to a Foreign Classmate That 'Giant Pandas Are More Than Just Cute Animals'", "type": "cultural_explanation", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际同学/朋友", "difficulty": 1, "knowledge_tags": '["nat_001"]', "scenario": "你的外国同学看到大熊猫照片说'好可爱！'请用英文简要介绍大熊猫在生态保护和国际交流中的重要意义，帮助他超越'可爱'的表面印象。"},
        {"title_zh": "用英文描述你最喜欢的四川美食", "title_en": "Describe Your Favorite Sichuan Dish in English", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际美食爱好者", "difficulty": 1, "knowledge_tags": '["ich_003"]', "scenario": "在一次国际青年交流活动的聚餐环节，外国朋友请你推荐一道最值得尝试的四川菜。请用英文介绍这道菜的口味、食材和吃法。"},
        {"title_zh": "向外国游客介绍四川的'火锅文化'", "title_en": "Introducing Sichuan 'Hotpot Culture' to Foreign Tourists", "type": "cultural_explanation", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "初次体验火锅的外国游客", "difficulty": 1, "knowledge_tags": '["ich_003"]', "scenario": "你带一群刚来成都的外国游客吃火锅，他们看到翻滚的红汤有些紧张。请用英文简单介绍火锅的吃法、社交意义和'围炉而坐'的文化。"},

        # 入门 - 即兴串场题
        {"title_zh": "校园国际文化节：中国书法展示与川剧变脸表演之间的串场", "title_en": "Campus International Culture Festival: Bridging a Chinese Calligraphy Demo and a Face-Changing Performance", "type": "impromptu_bridge", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "大学校园内的国际学生和教师", "difficulty": 1, "knowledge_tags": '["ich_001"]', "scenario": "你的大学正在举办国际文化节，上一个节目是中国书法表演，下一个是川剧变脸。作为学生主持人，用中英双语简单串场。"},
        {"title_zh": "国际学生迎新晚会：自我介绍加欢迎新同学", "title_en": "International Student Orientation: Self-Introduction and Welcoming New Students", "type": "impromptu_bridge", "module": "city_spirit", "language_direction": "bilingual", "target_audience": "来自各国的大学新生", "difficulty": 1, "knowledge_tags": '[]', "scenario": "你作为学生代表主持国际学生迎新晚会，需要先用中英双语做自我介绍，然后欢迎来自30个国家的新同学来到四川求学。"},

        # 入门 - 跨文化评论题
        {"title_zh": "为什么中国人喜欢喝热水？", "title_en": "Why Do Chinese People Like Drinking Hot Water?", "type": "cross_cultural_commentary", "module": "cultural_comparison", "language_direction": "en_to_zh", "target_audience": "国际友人/同学", "difficulty": 1, "knowledge_tags": '[]', "scenario": "你的外国室友发现你总是喝热水，感到非常困惑——'这不是很奇怪吗？'请用英文简要解释中国人的饮水习惯，用轻松的方式消解文化差异。"},
        {"title_zh": "外国朋友说'筷子很难用'——如何回应？", "title_en": "Foreign Friend Says 'Chopsticks Are Difficult to Use' — How to Respond?", "type": "cross_cultural_commentary", "module": "cultural_comparison", "language_direction": "en_to_zh", "target_audience": "国际朋友/同学", "difficulty": 1, "knowledge_tags": '[]', "scenario": "你的美国朋友在中餐馆抱怨'为什么不用叉子，筷子太难用了'。请用英文回应，从文化工具的角度解释筷子的设计哲学和使用价值。"},
        {"title_zh": "熊猫为什么是黑白色的？用最简单的语言介绍", "title_en": "Why Are Pandas Black and White? A Simple Explanation", "type": "cross_cultural_commentary", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际儿童/青少年", "difficulty": 1, "knowledge_tags": '["nat_001"]', "scenario": "在一场面向国际中小学生的线上课堂上，一个孩子问'为什么大熊猫是黑色和白色的？'请用英文以简单易懂的方式回答。"},

        # 入门 - 访谈应对题
        {"title_zh": "采访你身边一位来自不同国家的同学", "title_en": "Interview a Classmate from a Different Country", "type": "interview", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "校园国际社群", "difficulty": 1, "knowledge_tags": '[]', "scenario": "在校园'跨文化对话'节目中，你用中英双语采访一位来自巴西的同学，请他分享初到四川的第一印象和文化冲击——从饮食到天气到生活节奏。"},
        {"title_zh": "采访学校食堂的川菜大厨", "title_en": "Interview the Sichuan Cuisine Chef at Your School Cafeteria", "type": "interview", "module": "intangible_heritage", "language_direction": "bilingual", "target_audience": "校内国际师生", "difficulty": 1, "knowledge_tags": '["ich_003"]', "scenario": "你主持校园美食节目，用双语采访学校食堂的川菜大厨——一个做了30年川菜的老师傅。请用简单的问答形式介绍他最拿手的三道菜。"},

        # 入门 - 危机救场题
        {"title_zh": "课堂展示中PPT突然乱码", "title_en": "PPT Suddenly Shows Garbled Text During Class Presentation", "type": "crisis_rescue", "module": "cultural_comparison", "language_direction": "en_to_zh", "target_audience": "国际课程的同班同学", "difficulty": 1, "knowledge_tags": '[]', "scenario": "在一门国际课程的英文展示中，你的PPT突然变成乱码。你有30秒时间来化解尴尬——用英文说几句轻松的话稳住观众，然后用口头方式继续你的主题。"},
        {"title_zh": "校园国际日上展板被风吹倒", "title_en": "Exhibition Board Falls Over in the Wind at Campus International Day", "type": "crisis_rescue", "module": "city_spirit", "language_direction": "bilingual", "target_audience": "校园师生与访客", "difficulty": 1, "knowledge_tags": '[]', "scenario": "在校园国际日活动中，你负责的巴蜀文化展板突然被大风吹倒。周围各国同学都在看你。请用双语幽默化解——'看来四川的风也想参与今天的文化交流'。"},

        # 入门 - 观点辩论题
        {"title_zh": "养大熊猫当宠物好吗？", "title_en": "Is It a Good Idea to Keep a Giant Panda as a Pet?", "type": "debate", "module": "natural_heritage", "language_direction": "en_to_zh", "target_audience": "国际中小学生/青少年", "difficulty": 1, "knowledge_tags": '["nat_001"]', "scenario": "在国际学校的小学课堂上，一个外国孩子举手说'我好想养一只大熊猫当宠物！'作为这堂课的学生助教，请用英文温和地解释为什么大熊猫不适合当宠物，以及它们在野外的真实生活。"},
        {"title_zh": "四川火锅还是北京烤鸭更适合第一次来中国的外国人？", "title_en": "Sichuan Hotpot or Peking Duck: Which Is Better for a Foreigner's First Visit to China?", "type": "debate", "module": "intangible_heritage", "language_direction": "en_to_zh", "target_audience": "国际美食爱好者", "difficulty": 1, "knowledge_tags": '["ich_003"]', "scenario": "在国际学生群里，有人说应该带第一次来中国的外国朋友吃北京烤鸭（'不辣、安全'），你说应该吃四川火锅（'辣才是真正的中国味道'）。请用英文友好地辩论——为什么火锅值得一试。"},
        {"title_zh": "学中文好还是学英文好？一个双语主持人的观点", "title_en": "Learning Chinese vs Learning English: A Bilingual Host's Perspective", "type": "debate", "module": "cultural_comparison", "language_direction": "bilingual", "target_audience": "国际语言学习者", "difficulty": 1, "knowledge_tags": '[]', "scenario": "在一个语言学习分享会上，有人说'现在全世界都在学英文，中国人学好英文就够了，不用强推中文'。作为双语主持人，请用中英双语友好地回应——强调双语能力的不可替代价值。"},
        {"title_zh": "拍美食照片发社交媒体是'不礼貌'还是'文化传播'？", "title_en": "Is Taking Food Photos for Social Media 'Rude' or 'Cultural Sharing'?", "type": "debate", "module": "cultural_comparison", "language_direction": "en_to_zh", "target_audience": "国际青年/社交媒体用户", "difficulty": 1, "knowledge_tags": '[]', "scenario": "在一家中餐馆，你的外国朋友看到我们'先拍照后吃饭'感到很不理解，认为这是不礼貌的。请用英文友好地解释——在中国当代文化中，美食分享是一种社交仪式和传播方式。"},
        {"title_zh": "外国游客来四川三天：去大城市还是去小乡村？", "title_en": "Three Days in Sichuan for a Foreign Tourist: Big Cities or Small Villages?", "type": "debate", "module": "city_spirit", "language_direction": "en_to_zh", "target_audience": "国际旅游爱好者", "difficulty": 1, "knowledge_tags": '[]', "scenario": "你的外国朋友只有三天时间游四川，有人建议去成都+重庆两个大城市，你建议去成都周边的古镇和乡村。请用英文友好地论证你的'小地方更有味道'的观点。"},
    ]

    count = 0
    for data in seed_data:
        q = Question(**data)
        db.add(q)
        count += 1

    db.commit()
    return count
